'''
Code was adapted from the article "Drag & Drop Widgets with PySide6"
by Martin Fitzpatrick found at https://www.pythonguis.com/faq/pyside6-drag-drop-widgets/
This file includes content generated by ChatGPT (OpenAI, 2025)
'''

from PySide6.QtCore import (
    Qt,
    Signal,
    QPoint,
    QPropertyAnimation,
    QEasingCurve,
)
from PySide6.QtGui import QColor
from PySide6.QtWidgets import (
    QApplication,
    QLabel,
    QWidget,
    QMainWindow,
    QVBoxLayout,
    QHBoxLayout,
    QPushButton,
    QInputDialog,
    QMessageBox,
    QGraphicsDropShadowEffect,
    QSizePolicy,
    QSplitter,
    QStackedLayout,
    QGraphicsOpacityEffect,
    QScrollArea, QDialog,
)

# Import the interaction + MedlinePlus logic
from interaction_xml_parser import get_drug_interactions
from medline_plus_parsing import extract_medline_data

class StartupDialog(QDialog):
    '''
    Defines the startup dialog with the disclosure and how-to information
    The application cannot be used until this popup is closed
    '''
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Welcome to the Drug Interaction Study GUI!")
        layout = QVBoxLayout()
        layout.addWidget(QLabel("DISCLAIMER: This information is not intended to be used for real medical purposes"))
        layout.addWidget(QLabel("This is purely a study tool for students learning about drug interactions"))
        layout.addWidget(QLabel("HOW TO: Drag widgets until they overlap and study their interactions with using" +
                                " the flash cards in the bottom panel!"))
        close_button = QPushButton("Close")
        close_button.clicked.connect(self.accept)
        layout.addWidget(close_button)
        self.setLayout(layout)
        self.setStyleSheet(
            '''
            background-color: #001f3f;
            color: #e6f2ff;
            font-size: 16px;
            '''
        )


class DragComponent(QLabel):
    '''
    Defines the UI components used to hold the drug labels
    '''
    moved = Signal()

    def __init__(self, text, parent=None):
        super().__init__(text, parent)
        self.setContentsMargins(25, 5, 25, 5)
        self.setAlignment(Qt.AlignmentFlag.AlignCenter)

        # Define the stylesheets for the drug label default and after overlap
        self.default_stylesheet = """
            QLabel {
                background-color: #001f3f;
                color: #e6f2ff;
                border: 2px solid #3399ff;
                border-radius: 10px;
                font-size: 16px;
            }
            QLabel:hover {
                border: 2px solid #66b3ff;
            }
        """
        self.overlap_stylesheet = """
            QLabel {
                background-color: #001f3f;
                color: #e6f2ff;
                border: 2px solid #ff9900;
                border-radius: 10px;
                font-size: 16px;
            }
            QLabel:hover {
                border: 2px solid #ffb84d;
            }
        """
        self.setStyleSheet(self.default_stylesheet)

        # Add a glow effect to all widgets
        glow = QGraphicsDropShadowEffect(self)
        glow.setBlurRadius(25)
        glow.setColor(QColor("#3399ff"))
        glow.setOffset(0, 0)
        self.setGraphicsEffect(glow)

        self._drag_offset = QPoint(0, 0)
        self._is_overlapping = False

    def set_overlapping(self, overlapping: bool):
        # Change the outline to orange if the drug component overlaps with another drug component
        if self._is_overlapping == overlapping:
            return

        self._is_overlapping = overlapping

        if overlapping:
            self.setStyleSheet(self.overlap_stylesheet)
            effect = self.graphicsEffect()
            if isinstance(effect, QGraphicsDropShadowEffect):
                effect.setColor(QColor("#ff9900"))
        else:
            self.setStyleSheet(self.default_stylesheet)
            effect = self.graphicsEffect()
            if isinstance(effect, QGraphicsDropShadowEffect):
                effect.setColor(QColor("#3399ff"))

    # The following three functions handle the case where a components is dragged across the window
    def mousePressEvent(self, e):
        if e.button() == Qt.LeftButton:
            # Remember where inside the widget the click occurred
            self._drag_offset = e.position().toPoint()
            # Bring to front
            self.raise_()

    def mouseMoveEvent(self, e):
        if e.buttons() & Qt.LeftButton:
            new_pos = self.mapToParent(e.position().toPoint() - self._drag_offset)
            self.move(new_pos)

    def mouseReleaseEvent(self, e):
        super().mouseReleaseEvent(e)
        self.moved.emit()

class Canvas(QWidget):
    '''
    Defines the area where components are added and moved
    '''
    overlapped = Signal(str, str)

    def __init__(self, parent=None):
        super().__init__(parent)
        self.items = []
        self.setMinimumSize(400, 0)
        self.setStyleSheet(
            """
                background-color: #001733;
                border: 1px solid #333333;
            """
        )

    def add_component(self, text):
        # Handle the creation of a new component
        comp = DragComponent(text, self)
        comp.adjustSize()

        # Simple staggered starting positions
        offset = 50 * len(self.items)
        start_pos = QPoint(40 + offset, 40 + offset)
        comp.move(start_pos)
        comp.show()

        comp.moved.connect(self.check_overlaps)
        self.items.append(comp)

    def check_overlaps(self):
        # Track and check which components are overlapping
        overlapped_components = set()

        # Check all pairs for intersection
        for i in range(len(self.items)):
            for j in range(i + 1, len(self.items)):
                a = self.items[i]
                b = self.items[j]
                if a.geometry().intersects(b.geometry()):
                    overlapped_components.add(a)
                    overlapped_components.add(b)
                    # Emit signal with their labels
                    self.overlapped.emit(a.text(), b.text())

        for item in self.items:
            item.set_overlapping(item in overlapped_components)

class FlashCards(QWidget):
    '''
    Widget to mimic flashcards for study purposes
    '''
    def __init__(self, front_text: str, back_text: str, parent=None):
        super().__init__(parent)

        self.front_label = QLabel(front_text)
        self.back_label = QLabel(back_text)

        for lbl in (self.front_label, self.back_label):
            lbl.setAlignment(Qt.AlignCenter)
            lbl.setWordWrap(True)
            lbl.setStyleSheet(
                """
                QLabel {
                    background-color: #001f3f;
                    color: #e6f2ff;
                    border: 2px solid #3399ff;
                    border-radius: 10px;
                    font-size: 16px;
                }
                QLabel:hover {
                    border: 2px solid #66b3ff;
                }
                """
            )
            lbl.setAttribute(Qt.WidgetAttribute.WA_TransparentForMouseEvents)

        # Mimic flashcards with stacked labels
        self.stack = QStackedLayout()
        self.stack.addWidget(self.front_label)
        self.stack.addWidget(self.back_label)
        self.stack.setCurrentIndex(0)
        root_layout = QVBoxLayout(self)
        root_layout.addLayout(self.stack)

        # Add effects and animations to the flash cards to mimic the "flip"
        self.effect = QGraphicsOpacityEffect(self)
        self.setGraphicsEffect(self.effect)
        self.anim = QPropertyAnimation(self.effect, b"opacity", self)
        self.anim.setDuration(200)
        self.anim.setEasingCurve(QEasingCurve.InOutQuad)
        self.anim.finished.connect(self._on_anim_finished)
        self._fading_out = False
        self._is_front = True
        self.setMinimumSize(220, 120)

    def mousePressEvent(self, event):
        # Handle when the card is clicked
        if event.button() == Qt.LeftButton:
            self.flip()
        super().mousePressEvent(event)

    def flip(self):
        # Mimic the card flip
        self._fading_out = True
        self.anim.stop()
        self.anim.setStartValue(1.0)
        self.anim.setEndValue(0.0)
        self.anim.start()

    def _on_anim_finished(self):
        # Animations for the card "flip"
        if self._fading_out:
            # Swap side when fully transparent
            self._is_front = not self._is_front
            self.stack.setCurrentIndex(0 if self._is_front else 1)

            # Fade back in
            self._fading_out = False
            self.anim.stop()
            self.anim.setStartValue(0.0)
            self.anim.setEndValue(1.0)
            self.anim.start()

class ResultsPanel(QWidget):
    '''
    Panel that contains all the flash cards of drug interactions and side effects
    '''
    def __init__(self, parent=None):
        super().__init__(parent)

        self.container = QWidget()
        self.vlayout = QVBoxLayout(self.container)
        self.vlayout.setAlignment(Qt.AlignTop)

        self.scroll = QScrollArea()
        self.scroll.setWidgetResizable(True)
        self.scroll.setWidget(self.container)

        root_layout = QVBoxLayout(self)
        root_layout.addWidget(self.scroll)
        self.setStyleSheet(
            """
            background-color: #000066;
            color: #ffffff;
            border: 1px solid #555555;
            """
        )

    def add_flashcard(self, front_text: str, back_text: str):
        # Add flashcards to the results panel
        card = FlashCards(front_text, back_text)
        self.vlayout.addWidget(card)
        return card


class MainWindow(QMainWindow):
    '''
    Define the main window combining the canvas where drugs are moved and the results panel
    '''
    def __init__(self):
        super().__init__()
        self.setGeometry(100, 100, 1200, 800)
        self.setWindowTitle("Drug Interaction Explorer")
        self.canvas = Canvas(self)

        # Create the add button for drug components
        self.add_button = QPushButton("Add Drug")
        self.add_button.clicked.connect(self.add_new_component)
        self.add_button.setFixedHeight(48)
        self.add_button.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        self.add_button.setStyleSheet(
            """
            QPushButton {
                background-color: #01264d;
                color: #ffffff;
                border-radius: 12px;
                padding: 8px 24px;
                font-size: 16px;
                font-weight: bold;
            }
            QPushButton:hover {
                background-color: #055bb5;
            }
            QPushButton:pressed {
                background-color: #0053A6;
            }
            """
        )

        # Add a glow to the add button
        glow = QGraphicsDropShadowEffect(self)
        glow.setBlurRadius(20)
        glow.setColor(QColor("#3399ff"))
        glow.setOffset(0, 0)
        self.add_button.setGraphicsEffect(glow)

        # Create the results panel
        self.results_panel = ResultsPanel()

        # Adding all widgets to the central container
        container = QWidget()
        layout = QVBoxLayout(container)
        button_row = QHBoxLayout()
        button_row.addStretch()
        button_row.addWidget(self.add_button)
        layout.addLayout(button_row)

        # Add a splitter for adjustable panels
        splitter = QSplitter(Qt.Vertical)
        splitter.addWidget(self.canvas)
        splitter.addWidget(self.results_panel)
        splitter.setSizes([600, 400])
        layout.addWidget(splitter)

        self.setCentralWidget(container)

        # Pre-populate a few drugs
        for name in ["caffeine", "aspirin", "acetaminophen"]:
            self.canvas.add_component(name)

        # Connect overlap signal to logic
        self.canvas.overlapped.connect(self.handle_overlap)

        # Track which pairs we've already processed to avoid duplicate work
        self._seen_pairs = set()

    def add_new_component(self):
        # Add a new drug component by prompting the user for the drug name
        dlg = QInputDialog(self)
        dlg.setWindowTitle("New Drug")
        dlg.setLabelText("Enter drug name:")
        dlg.setStyleSheet(
            """
            QInputDialog {
                background-color: #001733;
                color: #e6f2ff;
            }

            QLabel {
                color: #e6f2ff;
                font-size: 16px;
            }
            
            QPushButton {
                background-color: #01264d;
                color: white;
                border-radius: 8px;
                padding: 6px 14px;
                font-weight: bold;
            }

            QPushButton:hover {
                background-color: #055bb5;
            }

            QPushButton:pressed {
                background-color: #004a99;
            }
            """
        )

        ok = dlg.exec()
        if ok:
            name = dlg.textValue().strip()
            if name:
                self.canvas.add_component(name)

    def handle_overlap(self, name1, name2):
        # Define what to do when drug components overlap
        key = tuple(sorted((name1.lower(), name2.lower())))
        if key in self._seen_pairs:
            # Already processed this combo
            return
        # If not processed, add to _seen_pairs
        self._seen_pairs.add(key)

        # Run the interaction and MedlinePlus queries
        try:
            self.display_interaction_results(name1, name2)
        except Exception as e:
            # Show error in the GUI
            QMessageBox.warning(self, "Error", f"An error occurred:\n{e}")

    def display_interaction_results(self, drug1: str, drug2: str):
        # Use get_drug_interactions and extract_medline_data and display a combined summary in the GUI.

        # Drug-drug interaction from interaction_xml_parser
        interaction_array = get_drug_interactions(drug1, drug2)
        # [0] Drug 1, [1] Drug 2, [2] Severity, [3] URL, [4] Description, [5] Extras

        # Build interaction text
        if interaction_array and interaction_array[2] != "N/A":
            inter_text = []
            inter_text.append("DRUG–DRUG INTERACTION")
            inter_text.append(
                f"Drugs: {interaction_array[0]} and {interaction_array[1]}"
            )
            inter_text.append(f"Severity: {interaction_array[2]}")
            inter_text.append("")
            inter_text.append(interaction_array[4])  # description
            if interaction_array[3] and interaction_array[3] != "N/A":
                inter_text.append(f"Source: {interaction_array[3]}")
            interaction_section = "\n".join(inter_text)
        else:
            interaction_section = (
                f"No interaction found between {drug1} and {drug2} "
                f"(according to XML/Drugs.com scraper). This does not guarantee safety."
            )

        # Individual drug info from MedlinePlus
        med1_array = extract_medline_data(drug1)
        med2_array = extract_medline_data(drug2)
        med_sections = []

        def format_med_section(label: str, arr):
            # arr: [0] Drug 1 (title), [1] N/A, [2] N/A, [3] URL, [4] Description, [5] Extras
            if not arr:
                return f"{label}: No MedlinePlus data found."
            title = arr[0]
            url = arr[3]
            desc = arr[4]
            text = [f"{label}: {title}", ""]
            text.append(desc)
            if url and url != "N/A":
                text.append(f"Source: {url}")
            return "\n".join(text)

        med_sections.append(format_med_section("Drug 1 details", med1_array))
        med_sections.append(format_med_section("Drug 2 details", med2_array))

        self.results_panel.add_flashcard(f"interaction between {drug1} and {drug2}", interaction_section)
        self.results_panel.add_flashcard(f"{drug1} side effects", med_sections[0])
        self.results_panel.add_flashcard(f"{drug2} side effects", med_sections[1])


if __name__ == "__main__":
    app = QApplication([])

    # Show the startup dialog
    startup_dialog = StartupDialog()
    startup_dialog.exec()

    # Once the dialog is closed, display the main window
    w = MainWindow()
    w.show()
    app.exec()
